'use client';

/**
 * Reusable Founder-dashboard PDF export — dependency-free.
 *
 * Builds a branded, presentation-ready report (SHAHI SOLUTIONS) from the data a
 * dashboard ALREADY has in memory (no extra API calls) and prints it to PDF via
 * a hidden iframe + the browser's native print engine. The report HTML uses
 * explicit hex colours (not the app's Tailwind classes), so it is unaffected by
 * Tailwind v4 `oklch` colours that break DOM-rasterisers like html2canvas.
 *
 * Charts are captured from the live recharts SVGs and embedded as PNG images
 * (recharts uses explicit hex colours, so SVG→canvas→PNG is safe). Non-SVG
 * "charts" (funnels, leaderboards) are exported by their underlying data as
 * tables by the caller.
 *
 * The same service powers Projects, Sales, Developers and HR — one workflow,
 * one design. Browser-only (guards on `typeof window`).
 */

export interface ReportKpi { label: string; value: string | number }
export interface ReportTable {
  title: string;
  columns: string[];
  rows: (string | number)[][];
  note?: string;
  /** Optional per-column alignment (index-matched to `columns`); omit ⇒ left. */
  align?: ('left' | 'right')[];
}
export interface ReportChartImage {
  title: string;
  dataUrl: string;
  /** Optional caption under the title (mirrors the dashboard card's subtitle). */
  subtitle?: string;
  /**
   * Optional legend. Recharts legends in this app are HTML siblings of the <svg>,
   * so they are NOT part of the captured image — pass the same data/colours the
   * chart was given and it is re-rendered here as crisp text (chart left, legend
   * right). Charts without a legend render exactly as before.
   */
  legend?: { label: string; value: string | number; color: string }[];
}
export interface ReportFilter { label: string; value: string }

export interface DashboardReport {
  /** Human title shown in the report header, e.g. "Projects Dashboard". */
  dashboardName: string;
  /** Filename stem, e.g. "Projects_Dashboard" → Projects_Dashboard_2026-06-30.pdf */
  fileBase: string;
  /** Logged-in Founder/Admin name for the "Generated By" line. */
  generatedBy: string;
  filters?: ReportFilter[];
  kpis: ReportKpi[];
  charts?: ReportChartImage[];
  tables?: ReportTable[];
}

const COMPANY = 'SHAHI SOLUTIONS';

/** Local YYYY-MM-DD for the filename (date-granular, matches the spec). */
export function reportDateStamp(d: Date = new Date()): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

const escapeHtml = (s: unknown): string =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/* ───────────────────────── Chart capture (recharts SVG → PNG) ───────────────── */

/** Best-effort chart title from the SVG's surrounding card (heading or bold text). */
function deriveChartTitle(svg: Element): string | null {
  let el: Element | null = svg.parentElement;
  for (let i = 0; i < 6 && el; i++, el = el.parentElement) {
    const h = el.querySelector('h1,h2,h3,h4');
    const t = h?.textContent?.trim();
    if (t) return t;
  }
  // Fallback: a short bold/semibold label (HR cards use <p class="font-semibold">).
  el = svg.parentElement;
  for (let i = 0; i < 6 && el; i++, el = el.parentElement) {
    const cand = Array.from(el.querySelectorAll('p,span,div')).find((n) => {
      const cls = typeof n.className === 'string' ? n.className : (n.getAttribute('class') || '');
      const txt = (n.textContent || '').trim();
      return /font-(semibold|bold)/.test(cls) && txt.length > 1 && txt.length < 60 && !n.querySelector('svg');
    });
    if (cand) return (cand.textContent || '').trim();
  }
  return null;
}

/** Rasterise a self-contained SVG (recharts) to a white-background PNG data URL. */
async function svgToPng(svg: SVGSVGElement): Promise<string | null> {
  const rect = svg.getBoundingClientRect();
  const w = Math.max(1, Math.round(rect.width || Number(svg.getAttribute('width')) || 600));
  const h = Math.max(1, Math.round(rect.height || Number(svg.getAttribute('height')) || 300));

  const clone = svg.cloneNode(true) as SVGSVGElement;
  clone.setAttribute('width', String(w));
  clone.setAttribute('height', String(h));
  if (!clone.getAttribute('viewBox')) clone.setAttribute('viewBox', `0 0 ${w} ${h}`);
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  // Pin a font so SVG <text> rasterises consistently (recharts sets no family).
  const style = document.createElementNS('http://www.w3.org/2000/svg', 'style');
  style.textContent = 'text{font-family:Arial,Helvetica,sans-serif;}';
  clone.insertBefore(style, clone.firstChild);

  const xml = new XMLSerializer().serializeToString(clone);
  const src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(xml);

  const img = new Image();
  img.width = w;
  img.height = h;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error('chart image load failed'));
    img.src = src;
  });

  const scale = 2; // retina-crisp in the PDF
  const canvas = document.createElement('canvas');
  canvas.width = w * scale;
  canvas.height = h * scale;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  ctx.scale(scale, scale);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, w, h);
  ctx.drawImage(img, 0, 0, w, h);
  return canvas.toDataURL('image/png');
}

/**
 * Capture every recharts chart currently rendered under `root` as a titled PNG.
 * Skips any chart that fails to rasterise (the rest still export). Lucide icons
 * are plain <svg> too, but only recharts uses `.recharts-surface`, so icons are
 * never picked up.
 */
export async function captureRechartsImages(root: ParentNode = document): Promise<ReportChartImage[]> {
  if (typeof window === 'undefined') return [];
  const svgs = Array.from(root.querySelectorAll('svg.recharts-surface')) as SVGSVGElement[];
  const out: ReportChartImage[] = [];
  for (let i = 0; i < svgs.length; i++) {
    try {
      const dataUrl = await svgToPng(svgs[i]);
      if (dataUrl) out.push({ title: deriveChartTitle(svgs[i]) || `Chart ${i + 1}`, dataUrl });
    } catch {
      /* skip this chart, keep the rest */
    }
  }
  return out;
}

/* ───────────────────────── Report HTML + print ──────────────────────────────── */

function buildReportHtml(report: DashboardReport, filename: string): string {
  const now = new Date();
  const exportedAt = now.toLocaleString(undefined, {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  const filtersHtml = report.filters && report.filters.length
    ? `<div class="filters"><b>Filters applied:</b> ${report.filters
        .map((f) => `${escapeHtml(f.label)}: <b>${escapeHtml(f.value)}</b>`)
        .join(' &nbsp;•&nbsp; ')}</div>`
    : '';

  const kpisHtml = report.kpis && report.kpis.length
    ? `<h2 class="section">Key Metrics</h2><div class="kpis">${report.kpis
        .map((k) => `<div class="kpi"><div class="l">${escapeHtml(k.label)}</div><div class="v">${escapeHtml(k.value)}</div></div>`)
        .join('')}</div>`
    : '';

  const chartsHtml = report.charts && report.charts.length
    ? `<h2 class="section">Analytics &amp; Charts</h2><div class="charts">${report.charts
        .map((c) => {
          const sub = c.subtitle ? `<p class="csub">${escapeHtml(c.subtitle)}</p>` : '';
          const img = `<img src="${c.dataUrl}" alt="${escapeHtml(c.title)}" />`;
          if (!c.legend || !c.legend.length) {
            return `<div class="chart"><h3>${escapeHtml(c.title)}</h3>${sub}${img}</div>`;
          }
          const items = c.legend
            .map((l) => `<li><span class="k"><i style="background:${escapeHtml(l.color)}"></i>${escapeHtml(l.label)}</span><b>${escapeHtml(l.value)}</b></li>`)
            .join('');
          return `<div class="chart chart--wide"><h3>${escapeHtml(c.title)}</h3>${sub}<div class="chart-row">${img}<ul class="legend">${items}</ul></div></div>`;
        })
        .join('')}</div>`
    : '';

  const tablesHtml = (report.tables || [])
    .filter((t) => t.rows.length > 0)
    .map((t) => {
      const alignCls = (i: number) => (t.align?.[i] === 'right' ? ' class="r"' : '');
      const head = t.columns.map((c, i) => `<th${alignCls(i)}>${escapeHtml(c)}</th>`).join('');
      const body = t.rows
        .map((r) => `<tr>${r.map((cell, i) => `<td${alignCls(i)}>${escapeHtml(cell)}</td>`).join('')}</tr>`)
        .join('');
      return `<h2 class="section">${escapeHtml(t.title)}</h2>${t.note ? `<p class="note">${escapeHtml(t.note)}</p>` : ''}<div class="tbl-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
    })
    .join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${escapeHtml(filename)}</title>
<style>
  @page { size: A4 landscape; margin: 15mm 14mm 20mm; }
  @page { @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 9px; color: #94a3b8; } }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1e293b; font-size: 11px; line-height: 1.45; }
  .brandbar { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; margin-bottom: 6px; }
  .company { font-size: 20px; font-weight: 800; letter-spacing: .5px; color: #0f172a; }
  .company .sub { display: block; font-size: 10px; font-weight: 700; color: #6366f1; letter-spacing: 3px; margin-top: 2px; }
  .meta { text-align: right; font-size: 10px; color: #64748b; line-height: 1.6; }
  .meta .dash { font-size: 15px; font-weight: 800; color: #0f172a; margin-bottom: 2px; }
  .filters { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 8px 12px; margin-top: 12px; font-size: 10px; color: #475569; }
  .filters b { color: #0f172a; }
  h2.section { font-size: 13px; font-weight: 700; color: #0f172a; margin: 24px 0 10px; padding-bottom: 6px; border-bottom: 1px solid #e2e8f0; }
  h2.section:first-of-type { margin-top: 18px; }
  .note { font-size: 10px; color: #64748b; margin: -4px 0 10px; }
  .kpis { display: flex; flex-wrap: wrap; gap: 10px; }
  .kpi { flex: 1 1 150px; min-width: 150px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 13px; background: #fff; page-break-inside: avoid; }
  .kpi .l { font-size: 8.5px; text-transform: uppercase; letter-spacing: .5px; color: #64748b; font-weight: 700; }
  .kpi .v { font-size: 17px; font-weight: 800; color: #0f172a; margin-top: 3px; }
  /* Charts: compact 2-up grid. Each chart is capped in height and never grows to
     fill a half-empty row, so graphs stay small and evenly spaced (no oversized
     single chart hogging a page). */
  .charts { display: flex; flex-wrap: wrap; gap: 18px; align-items: flex-start; }
  .chart { flex: 0 1 calc(50% - 9px); max-width: calc(50% - 9px); border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 14px; background: #fff; page-break-inside: avoid; }
  .chart h3 { margin: 0 0 10px; font-size: 11px; font-weight: 700; color: #334155; }
  .chart img { display: block; margin: 0 auto; max-width: 100%; max-height: 200px; width: auto; height: auto; }
  .chart .csub { margin: -6px 0 10px; font-size: 9px; color: #64748b; }
  /* A chart that carries a legend reproduces its dashboard card: full-width row,
     larger graph on the left, legend on the right, vertically centred. Declared
     after the .chart img rule above so the taller cap wins (same specificity). */
  .chart--wide { flex: 1 1 100%; max-width: 100%; }
  .chart--wide .chart-row { display: flex; align-items: center; justify-content: center; gap: 30px; }
  .chart--wide img { margin: 0; max-height: 260px; }
  .legend { list-style: none; margin: 0; padding: 0; min-width: 200px; }
  .legend li { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 5px 0; border-bottom: 1px solid #f1f5f9; font-size: 11px; color: #334155; }
  .legend li:last-child { border-bottom: 0; }
  .legend .k { display: flex; align-items: center; gap: 8px; text-transform: capitalize; }
  .legend i { width: 9px; height: 9px; border-radius: 50%; display: inline-block; flex: 0 0 auto; }
  .legend b { color: #0f172a; font-weight: 700; }
  table { width: 100%; border-collapse: collapse; }
  thead { display: table-header-group; }
  th { background: #f1f5f9; color: #334155; font-size: 9px; text-transform: uppercase; letter-spacing: .4px; text-align: left; padding: 6px 8px; border-bottom: 1px solid #cbd5e1; }
  td { padding: 5px 8px; border-bottom: 1px solid #eef2f7; font-size: 10px; color: #334155; }
  th.r, td.r { text-align: right; }
  tr { page-break-inside: avoid; }
  .footer { position: fixed; bottom: 0; left: 0; right: 0; display: flex; justify-content: space-between; font-size: 8.5px; color: #94a3b8; padding: 4px 2px; border-top: 1px solid #e2e8f0; }
</style></head>
<body>
  <div class="brandbar">
    <div class="company">${COMPANY}<span class="sub">ENTERPRISE ERP</span></div>
    <div class="meta">
      <div class="dash">${escapeHtml(report.dashboardName)}</div>
      Exported: ${escapeHtml(exportedAt)}<br />
      Generated by: ${escapeHtml(report.generatedBy)}
    </div>
  </div>
  ${filtersHtml}
  ${kpisHtml}
  ${chartsHtml}
  ${tablesHtml}
  <div class="footer">
    <span>${COMPANY} · ${escapeHtml(report.dashboardName)}</span>
    <span>Confidential — generated ${escapeHtml(exportedAt)}</span>
  </div>
</body></html>`;
}

/**
 * Shared print core (single source of truth for every report type — dashboard AND
 * task): write the report HTML into a hidden iframe, wait for the document + all
 * embedded images to be ready, open the browser print dialog (Save as PDF), then
 * remove the iframe. The saved filename defaults to the HTML `<title>`. Keeping
 * this in ONE place is why a task report reuses the exact print engine without
 * duplicating any iframe/print logic.
 */
// iOS/iPadOS + iOS Chrome (all WebKit). iPadOS ≥13 reports "Macintosh", so pair the
// Mac UA with a touch check. WebKit ignores print() on a HIDDEN iframe, so those devices
// need a visible, laid-out print frame instead of the desktop 0×0 one.
function isIOS(): boolean {
  if (typeof navigator === 'undefined') return false;
  return /iP(hone|od|ad)/.test(navigator.userAgent) ||
    (navigator.maxTouchPoints > 1 && /Macintosh/.test(navigator.userAgent));
}

async function printHtmlToPdf(html: string): Promise<void> {
  if (typeof window === 'undefined') return;
  const ios = isIOS();

  const iframe = document.createElement('iframe');
  iframe.setAttribute('aria-hidden', 'true');
  iframe.style.position = 'fixed';
  iframe.style.border = '0';
  if (ios) {
    // Real on-screen layout so WebKit renders + prints THIS frame (a 0×0 iframe prints blank
    // or grabs the parent page on iOS). Covered while the iOS print/share sheet is up; removed
    // on cleanup below.
    iframe.style.inset = '0';
    iframe.style.width = '100%';
    iframe.style.height = '100%';
    iframe.style.background = '#fff';
    iframe.style.zIndex = '2147483647';
  } else {
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
  }
  document.body.appendChild(iframe);

  const win = iframe.contentWindow;
  const doc = iframe.contentDocument || win?.document;
  if (!win || !doc) {
    iframe.remove();
    throw new Error('Unable to create the print document.');
  }

  doc.open();
  doc.write(html);
  doc.close();

  // Wait for the document + every embedded image to be ready so nothing prints blank.
  await new Promise<void>((resolve) => {
    if (doc.readyState === 'complete') resolve();
    else win.addEventListener('load', () => resolve(), { once: true });
  });
  await Promise.all(
    Array.from(doc.images).map((img) =>
      img.complete
        ? Promise.resolve()
        : new Promise<void>((res) => { img.onload = img.onerror = () => res(); }),
    ),
  );
  // A short settle so layout/paint completes before the print snapshot.
  await new Promise((r) => setTimeout(r, 250));

  let cleaned = false;
  const cleanup = () => {
    if (cleaned) return;
    cleaned = true;
    setTimeout(() => iframe.remove(), 500);
  };
  win.addEventListener('afterprint', cleanup, { once: true });
  // iOS often skips afterprint — also remove the visible frame when the user returns from
  // the print/share sheet (parent window regains focus), so the overlay never lingers.
  if (ios) window.addEventListener('focus', cleanup, { once: true });
  // Fallback cleanup in case afterprint never fires (some browsers).
  setTimeout(cleanup, ios ? 8000 : 60000);

  win.focus();
  win.print();
}

/**
 * Render `report` and open the browser print dialog (Save as PDF). The iframe
 * title is the descriptive filename, so the saved file defaults to
 * `<fileBase>_<YYYY-MM-DD>.pdf`. The iframe is removed after printing.
 */
export async function exportDashboardPdf(report: DashboardReport): Promise<void> {
  if (typeof window === 'undefined') return;
  const filename = `${report.fileBase}_${reportDateStamp()}`;
  await printHtmlToPdf(buildReportHtml(report, filename));
}

/* ═══════════════════════ Task Report (Global My Tasks) ══════════════════════════
 * A DOCUMENT-shaped report (not a dashboard grid): branded header, labelled info
 * sections, an attachments table, the full chat thread and activity timeline, a
 * completion record and metadata. Reuses the SAME print engine (printHtmlToPdf),
 * the SAME branding + escapeHtml + reportDateStamp helpers, and the same
 * page-break-avoid / page-number / footer conventions as the dashboard report —
 * only the section HTML/CSS differs (a task is a document, not a chart grid). It
 * paginates automatically for long descriptions, hundreds of messages and large
 * timelines (every message / row / timeline item is `page-break-inside: avoid`).
 * ──────────────────────────────────────────────────────────────────────────── */

export interface TaskReportField { label: string; value: string }
export interface TaskReportMember { name: string; role?: string }
export interface TaskReportAttachment {
  fileName: string; fileType: string; fileSize: string;
  uploadedBy: string; uploadedDate: string; url?: string;
}
export interface TaskReportMessage {
  sender: string; date: string; time: string; body: string; mentions?: string;
}
export interface TaskReportActivity { user: string; action: string; timestamp: string }

export interface TaskReport {
  /** Filename stem, e.g. "Task_123" → Task_123_2026-07-20.pdf */
  fileBase: string;
  generatedBy: string;
  taskId: string | number;
  /** Internal reference shown in the header + metadata, e.g. "MT-123". */
  taskRef: string;
  title: string;
  /** Free-text task description (line breaks / bullets preserved via pre-wrap). */
  description: string;
  /** Basic info rows: Status, Priority, Due Date/Time, Created, Updated, Waiting Reason. */
  basic: TaskReportField[];
  /** Responsibility rows: Created By, In-Charge, Project, Department (where available). */
  responsibility: TaskReportField[];
  /** Assigned members, rendered as initial-avatar chips (the app has no avatar images). */
  members: TaskReportMember[];
  attachments: TaskReportAttachment[];
  chat: TaskReportMessage[];
  activities: TaskReportActivity[];
  /** Completion / approval rows — empty ⇒ the section is hidden. */
  completion: TaskReportField[];
  /** Read status, timestamps, internal reference. */
  metadata: TaskReportField[];
}

const initials = (name: string): string =>
  (name || '?').trim().split(/\s+/).slice(0, 2).map((w) => w[0]?.toUpperCase() ?? '').join('') || '?';

function fieldGrid(fields: TaskReportField[]): string {
  if (!fields.length) return '';
  return `<div class="grid">${fields
    .map((f) => `<div class="cell"><div class="l">${escapeHtml(f.label)}</div><div class="v">${escapeHtml(f.value) || '—'}</div></div>`)
    .join('')}</div>`;
}

function labelledBlock(label: string, inner: string): string {
  return `<div class="block"><div class="l">${escapeHtml(label)}</div>${inner}</div>`;
}

function buildTaskReportHtml(report: TaskReport, filename: string): string {
  const now = new Date();
  const exportedAt = now.toLocaleString(undefined, {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  const descHtml = report.description && report.description.trim()
    ? `<div class="prose">${escapeHtml(report.description)}</div>`
    : `<div class="prose muted">No description provided.</div>`;

  const membersHtml = report.members.length
    ? `<div class="members">${report.members
        .map((m) => `<span class="chip"><span class="ava">${escapeHtml(initials(m.name))}</span><span>${escapeHtml(m.name)}${m.role ? ` <em>· ${escapeHtml(m.role)}</em>` : ''}</span></span>`)
        .join('')}</div>`
    : '<p class="muted small">No members assigned.</p>';

  const attachmentsHtml = report.attachments.length
    ? `<div class="tbl-wrap"><table><thead><tr><th>File Name</th><th>Type</th><th>Size</th><th>Uploaded By</th><th>Uploaded</th><th>Link</th></tr></thead><tbody>${report.attachments
        .map((a) => `<tr><td>${escapeHtml(a.fileName)}</td><td>${escapeHtml(a.fileType)}</td><td>${escapeHtml(a.fileSize)}</td><td>${escapeHtml(a.uploadedBy)}</td><td>${escapeHtml(a.uploadedDate)}</td><td>${a.url ? `<a href="${escapeHtml(a.url)}">Open</a>` : '—'}</td></tr>`)
        .join('')}</tbody></table></div>`
    : '<p class="muted small">No attachments.</p>';

  const chatHtml = report.chat.length
    ? `<div class="thread">${report.chat
        .map((m) => `<div class="msg"><div class="mhead"><span class="who">${escapeHtml(m.sender)}</span><span class="when">${escapeHtml(m.date)} · ${escapeHtml(m.time)}</span></div><div class="prose bare">${escapeHtml(m.body)}</div>${m.mentions ? `<div class="mentions">Mentions: ${escapeHtml(m.mentions)}</div>` : ''}</div>`)
        .join('')}</div>`
    : '<p class="muted small">No messages.</p>';

  const timelineHtml = report.activities.length
    ? `<ul class="timeline">${report.activities
        .map((a) => `<li><span class="dot"></span><div class="ti"><div class="ta">${escapeHtml(a.action)}</div><div class="tm">${escapeHtml(a.user)} · ${escapeHtml(a.timestamp)}</div></div></li>`)
        .join('')}</ul>`
    : '<p class="muted small">No recorded activity.</p>';

  const completionHtml = report.completion.length
    ? `<h2 class="section">Completion Information</h2>${fieldGrid(report.completion)}`
    : '';

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${escapeHtml(filename)}</title>
<style>
  @page { size: A4 portrait; margin: 16mm 14mm 20mm; }
  @page { @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 9px; color: #94a3b8; } }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1e293b; font-size: 11px; line-height: 1.5; }
  .brandbar { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; margin-bottom: 10px; }
  .company { font-size: 19px; font-weight: 800; letter-spacing: .5px; color: #0f172a; }
  .company .sub { display: block; font-size: 9px; font-weight: 700; color: #6366f1; letter-spacing: 3px; margin-top: 2px; }
  .meta { text-align: right; font-size: 10px; color: #64748b; line-height: 1.6; }
  .meta .rt { font-size: 15px; font-weight: 800; color: #0f172a; margin-bottom: 2px; }
  .meta b { color: #0f172a; }
  .title-band { background: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #4f46e5; border-radius: 8px; padding: 10px 14px; margin-bottom: 4px; }
  .title-band .t { font-size: 15px; font-weight: 800; color: #0f172a; }
  .title-band .r { font-size: 10px; color: #64748b; margin-top: 2px; }
  h2.section { font-size: 13px; font-weight: 700; color: #0f172a; margin: 22px 0 10px; padding-bottom: 6px; border-bottom: 1px solid #e2e8f0; page-break-after: avoid; }
  .grid { display: flex; flex-wrap: wrap; gap: 10px; }
  .cell { flex: 1 1 44%; min-width: 210px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 8px 12px; background: #fff; page-break-inside: avoid; }
  .cell .l, .block > .l { font-size: 8.5px; text-transform: uppercase; letter-spacing: .5px; color: #64748b; font-weight: 700; }
  .cell .v { font-size: 12px; font-weight: 600; color: #0f172a; margin-top: 3px; white-space: pre-wrap; word-break: break-word; }
  .block { margin-top: 12px; }
  .block > .l { margin-bottom: 5px; }
  .prose { white-space: pre-wrap; word-break: break-word; font-size: 11px; color: #334155; border: 1px solid #eef2f7; background: #fff; border-radius: 8px; padding: 10px 12px; }
  .prose.bare { border: 0; padding: 0; background: transparent; border-radius: 0; }
  .muted { color: #94a3b8; }
  .small { font-size: 10px; }
  .members { display: flex; flex-wrap: wrap; gap: 8px; }
  .chip { display: inline-flex; align-items: center; gap: 6px; border: 1px solid #e2e8f0; border-radius: 999px; padding: 3px 11px 3px 3px; font-size: 10px; color: #334155; background: #fff; page-break-inside: avoid; }
  .chip .ava { width: 20px; height: 20px; border-radius: 50%; background: #eef2ff; color: #4f46e5; font-size: 8.5px; font-weight: 800; display: inline-flex; align-items: center; justify-content: center; }
  .chip em { color: #94a3b8; font-style: normal; }
  table { width: 100%; border-collapse: collapse; }
  thead { display: table-header-group; }
  th { background: #f1f5f9; color: #334155; font-size: 9px; text-transform: uppercase; letter-spacing: .4px; text-align: left; padding: 6px 8px; border-bottom: 1px solid #cbd5e1; }
  td { padding: 5px 8px; border-bottom: 1px solid #eef2f7; font-size: 10px; color: #334155; word-break: break-word; }
  td a { color: #4f46e5; text-decoration: none; }
  tr { page-break-inside: avoid; }
  .thread { display: flex; flex-direction: column; gap: 8px; }
  .msg { border: 1px solid #eef2f7; border-left: 3px solid #c7d2fe; border-radius: 8px; padding: 8px 12px; background: #fff; page-break-inside: avoid; }
  .msg .mhead { display: flex; justify-content: space-between; gap: 12px; margin-bottom: 4px; align-items: baseline; }
  .msg .who { font-weight: 700; color: #0f172a; font-size: 11px; }
  .msg .when { font-size: 9px; color: #94a3b8; white-space: nowrap; }
  .mentions { margin-top: 5px; font-size: 9px; color: #6366f1; }
  .timeline { list-style: none; margin: 0; padding: 0; }
  .timeline li { display: flex; gap: 10px; padding: 6px 0; border-bottom: 1px solid #f1f5f9; page-break-inside: avoid; }
  .timeline li:last-child { border-bottom: 0; }
  .timeline .dot { width: 9px; height: 9px; margin-top: 4px; border-radius: 50%; background: #4f46e5; flex: 0 0 auto; }
  .timeline .ta { font-size: 11px; color: #0f172a; font-weight: 600; }
  .timeline .tm { font-size: 9px; color: #94a3b8; margin-top: 1px; }
  .footer { position: fixed; bottom: 0; left: 0; right: 0; display: flex; justify-content: space-between; font-size: 8.5px; color: #94a3b8; padding: 4px 2px; border-top: 1px solid #e2e8f0; }
</style></head>
<body>
  <div class="brandbar">
    <div class="company">${COMPANY}<span class="sub">ENTERPRISE ERP</span></div>
    <div class="meta">
      <div class="rt">Task Report</div>
      Task ID: <b>${escapeHtml(report.taskRef)}</b><br />
      Exported: ${escapeHtml(exportedAt)}<br />
      Generated by: ${escapeHtml(report.generatedBy)}
    </div>
  </div>
  <div class="title-band">
    <div class="t">${escapeHtml(report.title)}</div>
    <div class="r">Reference ${escapeHtml(report.taskRef)} &nbsp;·&nbsp; Task #${escapeHtml(report.taskId)}</div>
  </div>

  <h2 class="section">Basic Information</h2>
  ${fieldGrid(report.basic)}
  ${labelledBlock('Description', descHtml)}

  <h2 class="section">Responsibility</h2>
  ${fieldGrid(report.responsibility)}
  ${labelledBlock('Assigned Members', membersHtml)}

  <h2 class="section">Attachments</h2>
  ${attachmentsHtml}

  <h2 class="section">Task Chat</h2>
  ${chatHtml}

  <h2 class="section">Activity Timeline</h2>
  ${timelineHtml}

  ${completionHtml}

  <h2 class="section">Metadata</h2>
  ${fieldGrid(report.metadata)}

  <div class="footer">
    <span>${COMPANY} · Task Report · ${escapeHtml(report.taskRef)}</span>
    <span>Confidential — generated ${escapeHtml(exportedAt)}</span>
  </div>
</body></html>`;
}

/**
 * Render a single task as a branded, multi-page PDF (Save as PDF). Reuses the same
 * hidden-iframe print engine as the dashboard report; the iframe `<title>` sets the
 * default filename `<fileBase>_<YYYY-MM-DD>.pdf`.
 */
export async function exportTaskPdf(report: TaskReport): Promise<void> {
  if (typeof window === 'undefined') return;
  const filename = `${report.fileBase}_${reportDateStamp()}`;
  await printHtmlToPdf(buildTaskReportHtml(report, filename));
}
