'use client';

/**
 * Reusable Founder-dashboard PDF export — dependency-free.
 *
 * Builds a branded, presentation-ready report (SHAHI SOLUTIONS) from the data a
 * dashboard ALREADY has in memory (no extra API calls) and prints it to PDF via
 * a hidden iframe + the browser's native print engine. The report HTML uses
 * explicit hex colours (not the app's Tailwind classes), so it is unaffected by
 * Tailwind v4 `oklch` colours that break DOM-rasterisers like html2canvas.
 *
 * Charts are captured from the live recharts SVGs and embedded as PNG images
 * (recharts uses explicit hex colours, so SVG→canvas→PNG is safe). Non-SVG
 * "charts" (funnels, leaderboards) are exported by their underlying data as
 * tables by the caller.
 *
 * The same service powers Projects, Sales, Developers and HR — one workflow,
 * one design. Browser-only (guards on `typeof window`).
 */

export interface ReportKpi { label: string; value: string | number }
export interface ReportTable { title: string; columns: string[]; rows: (string | number)[][]; note?: string }
export interface ReportChartImage { title: string; dataUrl: string }
export interface ReportFilter { label: string; value: string }

export interface DashboardReport {
  /** Human title shown in the report header, e.g. "Projects Dashboard". */
  dashboardName: string;
  /** Filename stem, e.g. "Projects_Dashboard" → Projects_Dashboard_2026-06-30.pdf */
  fileBase: string;
  /** Logged-in Founder/Admin name for the "Generated By" line. */
  generatedBy: string;
  filters?: ReportFilter[];
  kpis: ReportKpi[];
  charts?: ReportChartImage[];
  tables?: ReportTable[];
}

const COMPANY = 'SHAHI SOLUTIONS';

/** Local YYYY-MM-DD for the filename (date-granular, matches the spec). */
export function reportDateStamp(d: Date = new Date()): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

const escapeHtml = (s: unknown): string =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/* ───────────────────────── Chart capture (recharts SVG → PNG) ───────────────── */

/** Best-effort chart title from the SVG's surrounding card (heading or bold text). */
function deriveChartTitle(svg: Element): string | null {
  let el: Element | null = svg.parentElement;
  for (let i = 0; i < 6 && el; i++, el = el.parentElement) {
    const h = el.querySelector('h1,h2,h3,h4');
    const t = h?.textContent?.trim();
    if (t) return t;
  }
  // Fallback: a short bold/semibold label (HR cards use <p class="font-semibold">).
  el = svg.parentElement;
  for (let i = 0; i < 6 && el; i++, el = el.parentElement) {
    const cand = Array.from(el.querySelectorAll('p,span,div')).find((n) => {
      const cls = typeof n.className === 'string' ? n.className : (n.getAttribute('class') || '');
      const txt = (n.textContent || '').trim();
      return /font-(semibold|bold)/.test(cls) && txt.length > 1 && txt.length < 60 && !n.querySelector('svg');
    });
    if (cand) return (cand.textContent || '').trim();
  }
  return null;
}

/** Rasterise a self-contained SVG (recharts) to a white-background PNG data URL. */
async function svgToPng(svg: SVGSVGElement): Promise<string | null> {
  const rect = svg.getBoundingClientRect();
  const w = Math.max(1, Math.round(rect.width || Number(svg.getAttribute('width')) || 600));
  const h = Math.max(1, Math.round(rect.height || Number(svg.getAttribute('height')) || 300));

  const clone = svg.cloneNode(true) as SVGSVGElement;
  clone.setAttribute('width', String(w));
  clone.setAttribute('height', String(h));
  if (!clone.getAttribute('viewBox')) clone.setAttribute('viewBox', `0 0 ${w} ${h}`);
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  // Pin a font so SVG <text> rasterises consistently (recharts sets no family).
  const style = document.createElementNS('http://www.w3.org/2000/svg', 'style');
  style.textContent = 'text{font-family:Arial,Helvetica,sans-serif;}';
  clone.insertBefore(style, clone.firstChild);

  const xml = new XMLSerializer().serializeToString(clone);
  const src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(xml);

  const img = new Image();
  img.width = w;
  img.height = h;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error('chart image load failed'));
    img.src = src;
  });

  const scale = 2; // retina-crisp in the PDF
  const canvas = document.createElement('canvas');
  canvas.width = w * scale;
  canvas.height = h * scale;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  ctx.scale(scale, scale);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, w, h);
  ctx.drawImage(img, 0, 0, w, h);
  return canvas.toDataURL('image/png');
}

/**
 * Capture every recharts chart currently rendered under `root` as a titled PNG.
 * Skips any chart that fails to rasterise (the rest still export). Lucide icons
 * are plain <svg> too, but only recharts uses `.recharts-surface`, so icons are
 * never picked up.
 */
export async function captureRechartsImages(root: ParentNode = document): Promise<ReportChartImage[]> {
  if (typeof window === 'undefined') return [];
  const svgs = Array.from(root.querySelectorAll('svg.recharts-surface')) as SVGSVGElement[];
  const out: ReportChartImage[] = [];
  for (let i = 0; i < svgs.length; i++) {
    try {
      const dataUrl = await svgToPng(svgs[i]);
      if (dataUrl) out.push({ title: deriveChartTitle(svgs[i]) || `Chart ${i + 1}`, dataUrl });
    } catch {
      /* skip this chart, keep the rest */
    }
  }
  return out;
}

/* ───────────────────────── Report HTML + print ──────────────────────────────── */

function buildReportHtml(report: DashboardReport, filename: string): string {
  const now = new Date();
  const exportedAt = now.toLocaleString(undefined, {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  const filtersHtml = report.filters && report.filters.length
    ? `<div class="filters"><b>Filters applied:</b> ${report.filters
        .map((f) => `${escapeHtml(f.label)}: <b>${escapeHtml(f.value)}</b>`)
        .join(' &nbsp;•&nbsp; ')}</div>`
    : '';

  const kpisHtml = report.kpis && report.kpis.length
    ? `<h2 class="section">Key Metrics</h2><div class="kpis">${report.kpis
        .map((k) => `<div class="kpi"><div class="l">${escapeHtml(k.label)}</div><div class="v">${escapeHtml(k.value)}</div></div>`)
        .join('')}</div>`
    : '';

  const chartsHtml = report.charts && report.charts.length
    ? `<h2 class="section">Analytics &amp; Charts</h2><div class="charts">${report.charts
        .map((c) => `<div class="chart"><h3>${escapeHtml(c.title)}</h3><img src="${c.dataUrl}" alt="${escapeHtml(c.title)}" /></div>`)
        .join('')}</div>`
    : '';

  const tablesHtml = (report.tables || [])
    .filter((t) => t.rows.length > 0)
    .map((t) => {
      const head = t.columns.map((c) => `<th>${escapeHtml(c)}</th>`).join('');
      const body = t.rows
        .map((r) => `<tr>${r.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`)
        .join('');
      return `<h2 class="section">${escapeHtml(t.title)}</h2>${t.note ? `<p class="note">${escapeHtml(t.note)}</p>` : ''}<div class="tbl-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
    })
    .join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${escapeHtml(filename)}</title>
<style>
  @page { size: A4 landscape; margin: 14mm 12mm 18mm; }
  @page { @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 9px; color: #94a3b8; } }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1e293b; font-size: 11px; line-height: 1.4; }
  .brandbar { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; margin-bottom: 6px; }
  .company { font-size: 20px; font-weight: 800; letter-spacing: .5px; color: #0f172a; }
  .company .sub { display: block; font-size: 10px; font-weight: 700; color: #6366f1; letter-spacing: 3px; margin-top: 2px; }
  .meta { text-align: right; font-size: 10px; color: #64748b; line-height: 1.6; }
  .meta .dash { font-size: 15px; font-weight: 800; color: #0f172a; margin-bottom: 2px; }
  .filters { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 8px 12px; margin-top: 12px; font-size: 10px; color: #475569; }
  .filters b { color: #0f172a; }
  h2.section { font-size: 13px; font-weight: 700; color: #0f172a; margin: 18px 0 8px; padding-bottom: 5px; border-bottom: 1px solid #e2e8f0; }
  .note { font-size: 10px; color: #64748b; margin: -2px 0 8px; }
  .kpis { display: flex; flex-wrap: wrap; gap: 8px; }
  .kpi { flex: 1 1 150px; min-width: 150px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 9px 12px; background: #fff; page-break-inside: avoid; }
  .kpi .l { font-size: 8.5px; text-transform: uppercase; letter-spacing: .5px; color: #64748b; font-weight: 700; }
  .kpi .v { font-size: 18px; font-weight: 800; color: #0f172a; margin-top: 3px; }
  .charts { display: flex; flex-wrap: wrap; gap: 14px; }
  .chart { flex: 1 1 46%; min-width: 46%; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 12px; background: #fff; page-break-inside: avoid; }
  .chart h3 { margin: 0 0 8px; font-size: 11px; font-weight: 700; color: #334155; }
  .chart img { width: 100%; height: auto; display: block; }
  table { width: 100%; border-collapse: collapse; }
  thead { display: table-header-group; }
  th { background: #f1f5f9; color: #334155; font-size: 9px; text-transform: uppercase; letter-spacing: .4px; text-align: left; padding: 6px 8px; border-bottom: 1px solid #cbd5e1; }
  td { padding: 5px 8px; border-bottom: 1px solid #eef2f7; font-size: 10px; color: #334155; }
  tr { page-break-inside: avoid; }
  .footer { position: fixed; bottom: 0; left: 0; right: 0; display: flex; justify-content: space-between; font-size: 8.5px; color: #94a3b8; padding: 4px 2px; border-top: 1px solid #e2e8f0; }
</style></head>
<body>
  <div class="brandbar">
    <div class="company">${COMPANY}<span class="sub">ENTERPRISE ERP</span></div>
    <div class="meta">
      <div class="dash">${escapeHtml(report.dashboardName)}</div>
      Exported: ${escapeHtml(exportedAt)}<br />
      Generated by: ${escapeHtml(report.generatedBy)}
    </div>
  </div>
  ${filtersHtml}
  ${kpisHtml}
  ${chartsHtml}
  ${tablesHtml}
  <div class="footer">
    <span>${COMPANY} · ${escapeHtml(report.dashboardName)}</span>
    <span>Confidential — generated ${escapeHtml(exportedAt)}</span>
  </div>
</body></html>`;
}

/**
 * Render `report` and open the browser print dialog (Save as PDF). The iframe
 * title is the descriptive filename, so the saved file defaults to
 * `<fileBase>_<YYYY-MM-DD>.pdf`. The iframe is removed after printing.
 */
export async function exportDashboardPdf(report: DashboardReport): Promise<void> {
  if (typeof window === 'undefined') return;
  const filename = `${report.fileBase}_${reportDateStamp()}`;
  const html = buildReportHtml(report, filename);

  const iframe = document.createElement('iframe');
  iframe.setAttribute('aria-hidden', 'true');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);

  const win = iframe.contentWindow;
  const doc = iframe.contentDocument || win?.document;
  if (!win || !doc) {
    iframe.remove();
    throw new Error('Unable to create the print document.');
  }

  doc.open();
  doc.write(html);
  doc.close();

  // Wait for the document + every embedded chart image to be ready so nothing
  // prints blank.
  await new Promise<void>((resolve) => {
    if (doc.readyState === 'complete') resolve();
    else win.addEventListener('load', () => resolve(), { once: true });
  });
  await Promise.all(
    Array.from(doc.images).map((img) =>
      img.complete
        ? Promise.resolve()
        : new Promise<void>((res) => { img.onload = img.onerror = () => res(); }),
    ),
  );
  // A short settle so layout/paint completes before the print snapshot.
  await new Promise((r) => setTimeout(r, 250));

  let cleaned = false;
  const cleanup = () => {
    if (cleaned) return;
    cleaned = true;
    setTimeout(() => iframe.remove(), 500);
  };
  win.addEventListener('afterprint', cleanup, { once: true });
  // Fallback cleanup in case afterprint never fires (some browsers).
  setTimeout(cleanup, 60000);

  win.focus();
  win.print();
}
