'use client';

/**
 * SalesMeetingModal — create / edit modal for Sales Meetings.
 *
 * Mirrors the create-meeting modal inside the Development MeetingsClient, but:
 *  - has NO project requirement (sales meetings have no project);
 *  - adds the Sales linkages: Customer / Lead / Deal / Related Team (all optional);
 *  - sources Participants + Organizer from fetchUsers('sales') (Sales users only);
 *  - the Google Meet link is generated by the backend (we only show a hint / the
 *    existing link on edit). No attachments field (notes/action items only).
 */

import { useEffect, useMemo, useState } from 'react';
import { Modal } from '@/components/Modal';
import { Button } from '@/components/Button';
import {
  Users, CheckCircle2, Video, ListTodo, Plus, Trash2,
} from 'lucide-react';
import { classNames, formatTime } from '@/lib/utils';
import { useToast } from '@/lib/hooks/useToast';
import { useAuthContext } from '@/lib/context/AuthContext';
import {
  createSalesMeeting,
  updateSalesMeeting,
  type SalesMeeting,
  type CreateSalesMeetingPayload,
  type UpdateSalesMeetingPayload,
  type SalesActionItemInput,
} from '@/lib/api/salesMeetings';
import { fetchUsers, type UserDbResponse } from '@/lib/api/users';
import { fetchLeads } from '@/lib/api/leads';
import { fetchDeals, fetchSalesCustomers, type CustomerOption } from '@/lib/api/leadLifecycle';
import { fetchTeams } from '@/lib/api/salesTeams';
import type { Lead } from '@/lib/types/lead';
import type { Deal } from '@/lib/types/leadLifecycle';
import type { SalesTeam } from '@/lib/types/salesExecution';

interface SalesMeetingModalProps {
  isOpen: boolean;
  onClose: () => void;
  /** Meeting being edited, or null for create. */
  meeting?: SalesMeeting | null;
  /** Called after a successful create/update so the list/analytics can refresh. */
  onSaved: () => void;
  /** Optional preloaded sales-user list (avoids a duplicate fetch). */
  users?: UserDbResponse[];
}

// Sales-relevant default subset is surfaced first; full list still available.
const TYPE_OPTIONS: { value: string; label: string }[] = [
  { value: 'CLIENT_MEETING', label: 'Client Meeting' },
  { value: 'INTERNAL_DISCUSSION', label: 'Internal Discussion' },
  { value: 'OTHER', label: 'Other' },
  { value: 'DAILY_STANDUP', label: 'Daily Standup' },
  { value: 'SPRINT_PLANNING', label: 'Sprint Planning' },
  { value: 'SPRINT_REVIEW', label: 'Sprint Review' },
  { value: 'RETROSPECTIVE', label: 'Retrospective' },
  { value: 'BUG_REVIEW', label: 'Bug Review' },
  { value: 'EMERGENCY_MEETING', label: 'Emergency Meeting' },
];

const DURATION_OPTIONS = ['15', '30', '45', '60', '120'];
const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

const inputCls = 'w-full px-3 py-2 border border-gray-300 rounded-lg text-sm bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all placeholder:text-gray-400';

const AVATAR_COLORS = ['from-blue-500 to-blue-600', 'from-purple-500 to-purple-600', 'from-green-500 to-green-600', 'from-pink-500 to-pink-600', 'from-orange-500 to-orange-600'];
const initialsOf = (name: string) => name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();

type ActionItemRow = { title: string; assignedTo: string; dueDate: string; priority: string };

/** Compute "HH:mm" end time from a start time + duration in minutes. */
function computeEndTime(startTime: string, durationMin: number): string {
  if (!startTime || !durationMin || durationMin <= 0) return '';
  const [h, m] = startTime.split(':').map(Number);
  if (isNaN(h) || isNaN(m)) return '';
  const d = new Date();
  d.setHours(h, m + durationMin);
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
}

/** Derive a duration (minutes) from two "HH:mm" strings, wrapping past midnight. */
function diffMinutes(startTime: string, endTime: string): number {
  const start = new Date(`1970-01-01T${startTime}:00Z`);
  const end = new Date(`1970-01-01T${endTime}:00Z`);
  let diff = (end.getTime() - start.getTime()) / 60000;
  if (diff <= 0) diff += 24 * 60;
  return diff;
}

export function SalesMeetingModal({ isOpen, onClose, meeting, onSaved, users: usersProp }: SalesMeetingModalProps) {
  const { toast } = useToast();
  const { user } = useAuthContext();
  const isEdit = !!meeting;

  // Reference data
  const [users, setUsers] = useState<UserDbResponse[]>(usersProp ?? []);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [deals, setDeals] = useState<Deal[]>([]);
  const [customers, setCustomers] = useState<CustomerOption[]>([]);
  const [teams, setTeams] = useState<SalesTeam[]>([]);

  // Form fields
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [notes, setNotes] = useState('');
  const [meetingType, setMeetingType] = useState('CLIENT_MEETING');
  const [meetingDate, setMeetingDate] = useState('');
  const [startTime, setStartTime] = useState('');
  const [duration, setDuration] = useState('30');
  const [customDuration, setCustomDuration] = useState('');
  const [customerId, setCustomerId] = useState('');
  const [leadId, setLeadId] = useState('');
  const [dealId, setDealId] = useState('');
  const [teamId, setTeamId] = useState('');
  const [selectedAttendees, setSelectedAttendees] = useState<number[]>([]);
  const [actionItemRows, setActionItemRows] = useState<ActionItemRow[]>([]);

  const [titleError, setTitleError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Load reference data when the modal opens.
  useEffect(() => {
    if (!isOpen) return;
    if (!usersProp || usersProp.length === 0) {
      fetchUsers('sales').then(setUsers).catch(() => setUsers([]));
    } else {
      setUsers(usersProp);
    }
    fetchLeads().then(setLeads).catch(() => setLeads([]));
    fetchDeals().then(setDeals).catch(() => setDeals([]));
    fetchSalesCustomers().then(setCustomers).catch(() => setCustomers([]));
    fetchTeams().then(setTeams).catch(() => setTeams([]));
  }, [isOpen, usersProp]);

  // (Re)seed the form whenever the modal opens or the target meeting changes.
  useEffect(() => {
    if (!isOpen) return;
    setTitleError('');
    if (meeting) {
      setTitle(meeting.title);
      setDescription(meeting.description ?? '');
      setNotes(meeting.notes ?? '');
      setMeetingType(meeting.meetingType);
      setMeetingDate(meeting.meetingDate ? meeting.meetingDate.split('T')[0] : '');
      setStartTime(meeting.startTime ?? '');
      const diff = meeting.startTime && meeting.endTime ? diffMinutes(meeting.startTime, meeting.endTime) : 30;
      const durStr = DURATION_OPTIONS.includes(String(diff)) ? String(diff) : 'CUSTOM';
      setDuration(durStr);
      setCustomDuration(durStr === 'CUSTOM' ? String(diff) : '');
      setCustomerId(meeting.customerId != null ? String(meeting.customerId) : '');
      setLeadId(meeting.leadId != null ? String(meeting.leadId) : '');
      setDealId(meeting.dealId != null ? String(meeting.dealId) : '');
      setTeamId(meeting.teamId != null ? String(meeting.teamId) : '');
      setSelectedAttendees(Array.isArray(meeting.attendees) ? meeting.attendees.map(Number) : []);
      setActionItemRows([]);
    } else {
      setTitle('');
      setDescription('');
      setNotes('');
      setMeetingType('CLIENT_MEETING');
      setMeetingDate('');
      setStartTime('');
      setDuration('30');
      setCustomDuration('');
      setCustomerId('');
      setLeadId('');
      setDealId('');
      setTeamId('');
      setSelectedAttendees([]);
      setActionItemRows([]);
    }
  }, [isOpen, meeting]);

  const durationMin = duration === 'CUSTOM' ? parseInt(customDuration || '0', 10) : parseInt(duration, 10);
  const endTime = useMemo(() => computeEndTime(startTime, durationMin), [startTime, durationMin]);

  const addActionItem = () => setActionItemRows(prev => [...prev, { title: '', assignedTo: '', dueDate: '', priority: 'MEDIUM' }]);
  const updateActionItem = (i: number, patch: Partial<ActionItemRow>) =>
    setActionItemRows(prev => prev.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
  const removeActionItem = (i: number) => setActionItemRows(prev => prev.filter((_, idx) => idx !== i));

  const toggleAttendee = (id: number) =>
    setSelectedAttendees(prev => (prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (title.trim().length < 3) {
      setTitleError('Title must be at least 3 characters');
      return;
    }
    if (!meetingDate) {
      toast('Please select a meeting date', 'error');
      return;
    }
    if (!startTime) {
      toast('Please select a start time', 'error');
      return;
    }
    if (!durationMin || durationMin <= 0) {
      toast('Please provide a valid duration', 'error');
      return;
    }
    const computedEnd = computeEndTime(startTime, durationMin);
    if (!computedEnd) {
      toast('Could not compute end time — check start time/duration', 'error');
      return;
    }

    const toNumOrNull = (v: string): number | null => (v ? Number(v) : null);

    setIsSubmitting(true);
    try {
      if (isEdit && meeting) {
        const payload: UpdateSalesMeetingPayload = {
          title: title.trim(),
          description: description.trim() || undefined,
          notes: notes.trim() || undefined,
          meetingType,
          meetingDate,
          startTime,
          endTime: computedEnd,
          attendees: selectedAttendees,
          leadId: toNumOrNull(leadId),
          dealId: toNumOrNull(dealId),
          customerId: toNumOrNull(customerId),
          teamId: toNumOrNull(teamId),
        };
        await updateSalesMeeting(meeting.id, payload);
        toast(`"${title.trim()}" updated successfully!`, 'success');
      } else {
        const actionItems: SalesActionItemInput[] = actionItemRows
          .filter(r => r.title.trim() && r.assignedTo)
          .map(r => ({
            title: r.title.trim(),
            assignedTo: Number(r.assignedTo),
            dueDate: r.dueDate || undefined,
            priority: r.priority,
          }));
        const payload: CreateSalesMeetingPayload = {
          title: title.trim(),
          meetingType,
          meetingDate,
          startTime,
          endTime: computedEnd,
          attendees: selectedAttendees,
          leadId: toNumOrNull(leadId),
          dealId: toNumOrNull(dealId),
          customerId: toNumOrNull(customerId),
          teamId: toNumOrNull(teamId),
          ...(description.trim() ? { description: description.trim() } : {}),
          ...(notes.trim() ? { notes: notes.trim() } : {}),
          ...(actionItems.length ? { actionItems } : {}),
        };
        await createSalesMeeting(payload);
        toast(`"${title.trim()}" created successfully!`, 'success');
      }
      onSaved();
      onClose();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to save meeting.';
      toast(msg, 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={() => { if (!isSubmitting) onClose(); }}
      title={isEdit ? 'Edit Sales Meeting' : 'Schedule Sales Meeting'}
      size="lg"
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Title */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Meeting Title *</label>
          <input
            value={title}
            onChange={e => { setTitle(e.target.value); if (titleError) setTitleError(''); }}
            placeholder="e.g. Q3 Renewal Discussion with Acme"
            className={inputCls}
          />
          {titleError && <p className="text-xs text-red-500 mt-1">{titleError}</p>}
        </div>

        {/* Sales linkages */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Customer</label>
            <select value={customerId} onChange={e => setCustomerId(e.target.value)} className={inputCls}>
              <option value="">— None —</option>
              {customers.map(c => <option key={c.id} value={String(c.id)}>{c.name}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Lead</label>
            <select value={leadId} onChange={e => setLeadId(e.target.value)} className={inputCls}>
              <option value="">— None —</option>
              {leads.map(l => <option key={l.id} value={String(l.id)}>{l.title}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Deal</label>
            <select value={dealId} onChange={e => setDealId(e.target.value)} className={inputCls}>
              <option value="">— None —</option>
              {deals.map(d => <option key={d.id} value={String(d.id)}>{d.title}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Related Team</label>
            <select value={teamId} onChange={e => setTeamId(e.target.value)} className={inputCls}>
              <option value="">— None —</option>
              {teams.map(t => <option key={t.id} value={String(t.id)}>{t.name}</option>)}
            </select>
          </div>
        </div>

        {/* Organizer (display only) */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Organizer</label>
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg">
            <div className="w-7 h-7 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
              {(user?.name ?? 'U').charAt(0).toUpperCase()}
            </div>
            <span className="text-sm font-medium text-gray-700">{user?.name ?? 'Current User'}</span>
            <span className="ml-auto text-xs text-gray-400">You</span>
          </div>
        </div>

        {/* Type */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Meeting Type *</label>
          <select value={meetingType} onChange={e => setMeetingType(e.target.value)} className={inputCls}>
            {TYPE_OPTIONS.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
          </select>
        </div>

        {/* Schedule */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Date *</label>
            <input type="date" value={meetingDate} onChange={e => setMeetingDate(e.target.value)} className={inputCls} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Start Time *</label>
            <input type="time" value={startTime} onChange={e => setStartTime(e.target.value)} className={inputCls} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1.5">Duration *</label>
            <select value={duration} onChange={e => setDuration(e.target.value)} className={inputCls}>
              <option value="15">15 Minutes</option>
              <option value="30">30 Minutes</option>
              <option value="45">45 Minutes</option>
              <option value="60">1 Hour</option>
              <option value="120">2 Hours</option>
              <option value="CUSTOM">Custom Duration</option>
            </select>
          </div>
        </div>

        {duration === 'CUSTOM' && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">Custom Duration (Minutes) *</label>
              <input type="number" min="1" value={customDuration} onChange={e => setCustomDuration(e.target.value)} className={inputCls} placeholder="e.g. 90" />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1.5">End Time</label>
              <input value={endTime ? formatTime(endTime) : ''} disabled className={classNames(inputCls, 'bg-gray-50 text-gray-500 cursor-not-allowed')} />
            </div>
          </div>
        )}

        {duration !== 'CUSTOM' && endTime && (
          <div className="text-sm text-gray-500">
            <span className="font-semibold text-gray-700">Calculated End Time:</span> {formatTime(endTime)}
          </div>
        )}

        {/* Google Meet hint / existing link */}
        {isEdit && meeting?.meetingLink ? (
          <a
            href={meeting.meetingLink}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-xs text-green-700 bg-green-50 p-2 rounded-lg hover:underline"
          >
            <Video size={14} /> Existing Google Meet link — Join meeting
          </a>
        ) : (
          <div className="text-xs text-blue-600 flex items-center gap-1.5 bg-blue-50 p-2 rounded-lg">
            <Video size={14} /> A Google Meet link will be automatically generated for this meeting.
          </div>
        )}

        {/* Description */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Description</label>
          <textarea value={description} onChange={e => setDescription(e.target.value)} rows={2} placeholder="Meeting agenda or purpose..." className={classNames(inputCls, 'resize-none')} />
        </div>

        {/* Notes */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Notes</label>
          <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2} placeholder="Pre-meeting notes (optional)..." className={classNames(inputCls, 'resize-none')} />
        </div>

        {/* Participants */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1.5">
            <Users size={12} className="inline mr-1" />Participants
            {selectedAttendees.length > 0 && (
              <span className="ml-2 text-xs font-semibold px-2 py-0.5 rounded-full bg-blue-50 text-blue-600">{selectedAttendees.length} selected</span>
            )}
          </label>
          <div className="border border-gray-300 rounded-lg overflow-hidden">
            {users.length === 0 ? (
              <p className="text-xs text-gray-400 px-3 py-3 italic">No sales users available</p>
            ) : (
              <div className="max-h-44 overflow-y-auto divide-y divide-gray-100">
                {users.map(u => {
                  const checked = selectedAttendees.includes(u.id);
                  const color = AVATAR_COLORS[u.id % AVATAR_COLORS.length];
                  return (
                    <label key={u.id} className={classNames('flex items-center gap-3 px-3 py-2.5 cursor-pointer transition-colors select-none', checked ? 'bg-blue-50' : 'hover:bg-gray-50')}>
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() => toggleAttendee(u.id)}
                        className="w-4 h-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500 cursor-pointer"
                      />
                      <div className={`w-7 h-7 rounded-full bg-gradient-to-br ${color} flex items-center justify-center text-white text-[10px] font-bold flex-shrink-0`}>
                        {initialsOf(u.name)}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-gray-800 truncate">{u.name}</p>
                        <p className="text-xs text-gray-400 truncate">{u.email}</p>
                      </div>
                      {checked && <CheckCircle2 size={15} className="text-blue-500 flex-shrink-0" />}
                    </label>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Action items (create only — stored in DB with the meeting) */}
        {!isEdit && (
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-sm font-semibold text-gray-700"><ListTodo size={12} className="inline mr-1" />Action Items</label>
              <button type="button" onClick={addActionItem} className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-700">
                <Plus size={13} /> Add Item
              </button>
            </div>
            {actionItemRows.length === 0 ? (
              <p className="text-xs text-gray-400 italic">No action items. Add follow-up tasks for this meeting.</p>
            ) : (
              <div className="space-y-2">
                {actionItemRows.map((row, i) => (
                  <div key={i} className="grid grid-cols-1 sm:grid-cols-12 gap-2 items-center bg-gray-50 border border-gray-200 rounded-lg p-2">
                    <input value={row.title} onChange={e => updateActionItem(i, { title: e.target.value })}
                      placeholder="Action item title" className={classNames(inputCls, 'sm:col-span-4 !py-1.5')} />
                    <select value={row.assignedTo} onChange={e => updateActionItem(i, { assignedTo: e.target.value })}
                      className={classNames(inputCls, 'sm:col-span-3 !py-1.5')}>
                      <option value="">Assignee…</option>
                      {users.map(u => <option key={u.id} value={String(u.id)}>{u.name}</option>)}
                    </select>
                    <input type="date" value={row.dueDate} onChange={e => updateActionItem(i, { dueDate: e.target.value })}
                      className={classNames(inputCls, 'sm:col-span-2 !py-1.5')} />
                    <select value={row.priority} onChange={e => updateActionItem(i, { priority: e.target.value })}
                      className={classNames(inputCls, 'sm:col-span-2 !py-1.5')}>
                      {PRIORITIES.map(p => <option key={p} value={p}>{p.charAt(0) + p.slice(1).toLowerCase()}</option>)}
                    </select>
                    <button type="button" onClick={() => removeActionItem(i)} title="Remove"
                      className="sm:col-span-1 inline-flex items-center justify-center p-1.5 rounded-lg text-gray-400 hover:text-red-600 hover:bg-red-50 transition-all">
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        <div className="flex gap-3 pt-3 border-t border-gray-100">
          <Button type="button" variant="secondary" className="flex-1" onClick={onClose} disabled={isSubmitting}>Cancel</Button>
          <Button type="submit" variant="primary" className="flex-1" isLoading={isSubmitting}>
            {isEdit ? 'Update Meeting' : 'Schedule Meeting'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
